### ISSUE TITLE
Error Kotlin Gradle plugin version

### ISSUE THREAD

**Issue by jacobaraujo7** [YoussefKababe/pinch_zoom_image#2]
Hello.

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'pinch_zoom_image' is using version 1.2.30.

Please, upgrade package to Flutter v0.9.4.
Thanks

**Comment by YoussefKababe** [comment]
Hi there! How did you get that error? This package was indeed generated with Flutter v0.9.4. I tried to generate a new one and it has the same Kotlin plugin version (1.2.30). Should we just upgrade the Kotlin version in `build.gradle`?

**Comment by YoussefKababe** [comment]
Flutter 0.10.2 was just released and I upgraded the plugin to it. Problem seems to be solved now!
